/**
 * Collects the ABIs and addresses of every contract deployed with Hardhat
 * Ignition and writes them to the web app as a typed TypeScript module.
 *
 * Runs automatically after `npm run deploy:*`. Run manually with `npm run export`.
 */
import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const deploymentsDir = path.join(root, "ignition", "deployments");
const outFile = path.resolve(root, "../../apps/web/src/contracts/generated.ts");

type Entry = { abi: unknown[]; address: Record<number, string> };
const contracts: Record<string, Entry> = {};

if (existsSync(deploymentsDir)) {
  const chainDirs = (await readdir(deploymentsDir)).filter((d) =>
    d.startsWith("chain-"),
  );

  for (const dir of chainDirs) {
    const chainId = Number(dir.slice("chain-".length));
    const addressesFile = path.join(deploymentsDir, dir, "deployed_addresses.json");
    if (!existsSync(addressesFile)) continue;

    const addresses: Record<string, string> = JSON.parse(
      await readFile(addressesFile, "utf8"),
    );

    for (const [futureId, address] of Object.entries(addresses)) {
      const artifact = JSON.parse(
        await readFile(
          path.join(deploymentsDir, dir, "artifacts", `${futureId}.json`),
          "utf8",
        ),
      );
      const name: string = artifact.contractName;
      contracts[name] ??= { abi: artifact.abi, address: {} };
      contracts[name].address[chainId] = address;
    }
  }
}

const body = Object.entries(contracts)
  .map(
    ([name, { abi, address }]) =>
      `  ${name}: {\n    address: ${JSON.stringify(address)},\n    abi: ${JSON.stringify(abi)},\n  },`,
  )
  .join("\n");

await writeFile(
  outFile,
  `// AUTO-GENERATED by packages/contracts/scripts/export-contracts.ts. Do not edit.\n\n` +
    `export const contracts = {\n${body}\n} as const;\n`,
);

console.log(
  `Exported ${Object.keys(contracts).join(", ") || "no contracts"} to ${path.relative(process.cwd(), outFile)}`,
);
