// AUTO-GENERATED by packages/contracts/scripts/export-contracts.ts. Do not edit.

export const contracts = {
  Counter: {
    address: {"31337":"0x5FbDB2315678afecb367f032d93F642f64180aa3"},
    abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"by","type":"uint256"}],"name":"Increment","type":"event"},{"inputs":[],"name":"inc","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"by","type":"uint256"}],"name":"incBy","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"x","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}],
  },
} as const;
